### ISSUE TITLE
Please upload source code

### ISSUE THREAD

**Issue by mi-hol** [HAEdwin/ECUreader#2]
As an exe could destroy a Windows Computer easily, publishing the source code would increase trust in this solution a lot.
Would that be feasible?

**Comment by HAEdwin** [comment]
Sources are now available, no problem.

**Comment by mi-hol** [comment]
Is there a requirement/instruction on how to use "ECU Reader v18.exe"?
I tried to connect by IP (provided by my WiFi Router) but never succeeded.

**Comment by HAEdwin** [comment]
-done-
